version: "3.9"

services:

  app:
    container_name: app
    image: talkme-app:0.1
    volumes:
      - ~/projets/TalkMe/app:/usr/src/app
      - app-data:/node_modules
    ports:
      - 31000:3000
    restart: always

volumes:
  app-data:
